export enum ErrorCode {
  // Authentication
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',

  // Authorization / multi-tenancy
  INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION',
  CHURCH_ACCESS_DENIED = 'CHURCH_ACCESS_DENIED',
  CHURCH_CONTEXT_REQUIRED = 'CHURCH_CONTEXT_REQUIRED',

  // Domain rules
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CHURCH_SLUG_ALREADY_EXISTS = 'CHURCH_SLUG_ALREADY_EXISTS',
  TEAM_SLUG_ALREADY_EXISTS = 'TEAM_SLUG_ALREADY_EXISTS',
  TEAM_ROLE_SLUG_ALREADY_EXISTS = 'TEAM_ROLE_SLUG_ALREADY_EXISTS',
  TEAM_ROLE_NOT_IN_TEAM = 'TEAM_ROLE_NOT_IN_TEAM',
  DUPLICATE_SCHEDULE = 'DUPLICATE_SCHEDULE',
  INVALID_SCHEDULE_TRANSITION = 'INVALID_SCHEDULE_TRANSITION',
  MEMBER_UNAVAILABLE = 'MEMBER_UNAVAILABLE',
  SWAP_ALREADY_OPEN = 'SWAP_ALREADY_OPEN',
  SWAP_NOT_OPEN = 'SWAP_NOT_OPEN',
  INVALID_SWAP_CANDIDATE = 'INVALID_SWAP_CANDIDATE',
  INVALID_RECURRENCE_RULE = 'INVALID_RECURRENCE_RULE',
  EVENT_NOT_RECURRING = 'EVENT_NOT_RECURRING',

  // Persistence
  UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
  FOREIGN_KEY_VIOLATION = 'FOREIGN_KEY_VIOLATION',
  NOT_NULL_VIOLATION = 'NOT_NULL_VIOLATION',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // Generic fallbacks
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
